### ISSUE TITLE
on LM17.x Software Center Crashes When Opening Then Closing Software Sources From Within Software Manager

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/mintinstall#108] opened 2016-08-19 14:43 UTC
Software Manager > Software Sources > Close Software Sources Window, and then Software Manager closes automatically then a little while later opens back up as demonstrated at this point in this video https://youtu.be/Lf98FEV_Kvg?t=211 I'm not sure if this is a bug or just a broken implementation of reloading Software Manager, but I've noticed it for a very long time and just now reporting it on here. I appreciate the hard work from the Linux Mint team and thanks in advance.
ref: https://bugs.launchpad.net/linuxmint/+bug/1608777

**Comment by two-dogs** [comment] 2016-08-19 14:56
i cant reproduce on LM18

**Comment by robertzaccour** [comment] 2016-08-19 15:01
Original bug report.
https://bugs.launchpad.net/linuxmint/+bug/1608777

**Comment by Simon1NL** [comment] 2016-08-19 15:13
I can confirm issue on 17.3 

https://bugs.launchpad.net/linuxmint/+bug/1608777

System:    Host: simon-MS-7327 Kernel: 4.2.0-34-generic x86_64 (64 bit gcc: 4.8.2)
           Desktop: Cinnamon 2.8.8 (Gtk 3.10.8~8+qiana) dm: mdm Distro: Linux Mint 17.3 Rosa
Machine:   Mobo: MICRO-STAR INTERANTIONAL model: MS-7327 v: 1.0
           Bios: American Megatrends v: V1.3B1 date: 05/04/2007
CPU:       Dual core AMD Athlon 64 X2 5000+ (-MCP-) cache: 1024 KB flags: (lm nx sse sse2 sse3 svm) bmips: 3990 
           clock speeds: min/max: 1000/2600 MHz 1: 1000 MHz 2: 1000 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] RV730 PRO [Radeon HD 4650] bus-ID: 01:00.0 chip-ID: 1002:9498
           Display Server: X.Org 1.17.1 drivers: ati,radeon (unloaded: fbdev,vesa) Resolution: 1440x900@59.9hz
           GLX Renderer: Gallium 0.4 on AMD RV730 GLX Version: 3.0 Mesa 10.5.9 Direct Rendering: Yes
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] RV710/730 HDMI Audio [Radeon HD 4000 series]
           driver: snd_hda_intel bus-ID: 01:00.1 chip-ID: 1002:aa38
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel bus-ID: 00:14.2 chip-ID: 1002:4383
           Sound: Advanced Linux Sound Architecture v: k4.2.0-34-generic
Network:   Card: Realtek RTL8169 PCI Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: e800 bus-ID: 03:02.0 chip-ID: 10ec:8169
           IF: eth0 state: up speed: 100 Mbps duplex: full mac: d8:5d:4c:81:67:81
Drives:    HDD Total Size: 330.1GB (20.2% used)
           ID-1: /dev/sda model: WDC_WD2500AAKS size: 250.1GB serial: WD-WMART0673521
           ID-2: /dev/sdb model: ST380020A size: 80.0GB serial: 3GCM071T
Partition: ID-1: / size: 19G used: 5.9G (33%) fs: ext4 dev: /dev/sda1
           ID-2: /home size: 92G used: 49G (56%) fs: ext4 dev: /dev/sda5
           ID-3: swap-1 size: 8.59GB used: 0.00GB (0%) fs: swap dev: /dev/sda3
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 27.0C mobo: N/A gpu: 45.5
           Fan Speeds (in rpm): cpu: 3171 fan-2: 0 fan-3: 0 fan-4: 0
Repos:     Active apt sources in file: /etc/apt/sources.list.d/gwendal-lebihan-dev-hexchat-stable-trusty.list
           deb http://ppa.launchpad.net/gwendal-lebihan-dev/hexchat-stable/ubuntu trusty main
           deb-src http://ppa.launchpad.net/gwendal-lebihan-dev/hexchat-stable/ubuntu trusty main
           Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http://ftp.nluug.nl/os/Linux/distr/linuxmint/packages rosa main upstream import
           deb http://extra.linuxmint.com rosa main
           deb http://nl.archive.ubuntu.com/ubuntu trusty main restricted universe multiverse
           deb http://nl.archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse
           deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse
           deb http://archive.canonical.com/ubuntu/ trusty partner
Info:      Processes: 182 Uptime: 5:15 Memory: 1255.8/3952.7MB
           Init: Upstart v: 1.12.1 runlevel: 2 default: 2 Gcc sys: 4.8.4
           Client: Shell (bash 4.3.111 running in gnome-terminal) inxi: 2.3.0

**Comment by kneekoo** [comment] 2017-03-04 03:09
Live session Mint 18.1 MATE 64-bit, and mintinstall restarts after closing mintsources. However, it's not a crash but a simple restart of mintinstall. It looks like the Software Manager assumes that you will change something in Software Sources, so it _instructs_ mintinstall to restart, regardless of what the user does with mintsources.

**Comment by JosephMcc** [comment] 2017-07-28 20:24
Mintinstall needs to restart if you've changed the software sources but we can definitely do a better job of presenting to the user what is happening.

**Comment by kneekoo** [comment] 2017-07-29 08:59
Running Mint 18.2 with mintinstall 7.7.8. Once you start the **Software sources** from the **mintinstall** Edit menu, **Software Manager** closes down, it starts **Software sources**, then a few seconds later **Software Manager** starts back up on its own without doing anything whatsoever.

This doesn't make any sense from the user's perspective.

**Comment by clefebvre** [comment] 2017-08-07 12:00
This feature was removed in git master.

**Closed by clefebvre** 2017-08-07 12:00 UTC
