### ISSUE TITLE
Loading forever on start    Loading error: 'NoneType' object has no attribute 'verified'

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [linuxmint/mintinstall#422] opened 2024-05-15 00:31 UTC
OS: Ubuntu 22.04
DE/WM: both occurring on KDE Plasma and I3wm
Screenshot:
![Screenshot_20240515_102613](https://github.com/linuxmint/mintinstall/assets/68761233/4ad27302-6621-467d-9f51-78f50fef5c2b)
Output when I run "G_MESSAGES_DEBUG=all mintinstall":
```
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
(mintinstall.py:762255): GLib-GIO-DEBUG: 10:24:14.926: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(mintinstall.py:762255): GLib-GIO-DEBUG: 10:24:15.035: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(mintinstall.py:762255): dconf-DEBUG: 10:24:15.035: watch_fast: "/com/linuxmint/install/" (establishing: 0, active: 0)
MintInstall: Detected system architecture: 'x86_64'
(mintinstall.py:762255): dconf-DEBUG: 10:24:15.036: watch_established: "/com/linuxmint/install/" (establishing: 1)
(mintinstall.py:762255): GLib-DEBUG: 10:24:15.043: unsetenv() is not thread-safe and should not be used after threads are created
(mintinstall.py:762255): Gtk-DEBUG: 10:24:15.043: Connecting to session manager
(mintinstall.py:762255): Gtk-DEBUG: 10:24:15.044: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(mintinstall.py:762255): Gtk-DEBUG: 10:24:15.045: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(mintinstall.py:762255): fcitx-connection-DEBUG: 10:24:15.112: _fcitx_connection_create_ic
(mintinstall.py:762255): dconf-DEBUG: 10:24:15.120: watch_fast: "/com/linuxmint/install/" (establishing: 0, active: 1)
(mintinstall.py:762255): dconf-DEBUG: 10:24:15.128: watch_fast: "/com/linuxmint/install/" (establishing: 0, active: 2)
(mintinstall.py:762255): fcitx-connection-DEBUG: 10:24:15.399: _fcitx_connection_connection_finished
Loading error: 'NoneType' object has no attribute 'verified'
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1378, in on_installer_ready
    self.load_landing_apps()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1617, in load_landing_apps
    self.load_featured()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1547, in load_featured
    if not pkginfo.verified:
MintInstall: No new reviews
Loading error: 'NoneType' object has no attribute 'verified'
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1378, in on_installer_ready
    self.load_landing_apps()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1617, in load_landing_apps
    self.load_featured()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1547, in load_featured
    if not pkginfo.verified:
MintInstall: No new reviews
Loading error: 'NoneType' object has no attribute 'verified'
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1378, in on_installer_ready
    self.load_landing_apps()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1616, in load_landing_apps
    self.load_banner()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1439, in load_banner
    if not pkginfo.verified:
MintInstall: No new reviews
Loading error: 'NoneType' object has no attribute 'verified'
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1378, in on_installer_ready
    self.load_landing_apps()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1617, in load_landing_apps
    self.load_featured()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1547, in load_featured
    if not pkginfo.verified:
MintInstall: No new reviews
Loading error: 'NoneType' object has no attribute 'verified'
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1378, in on_installer_ready
    self.load_landing_apps()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1617, in load_landing_apps
    self.load_featured()
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1547, in load_featured
    if not pkginfo.verified:
MintInstall: No new reviews
```

**Comment by boga70** [comment] 2024-07-29 07:56
There are two lines "if not pkginfo.verified:" in mintinstall.py,  changed them to "if pkginfo is None or not pkginfo.verified:"

**Comment by mtwebster** [comment] 2024-07-29 13:42
Do you have the latest mint-common version also?

**Comment by boga70** [comment] 2024-07-29 18:37
It's 2.3.7, I've upgraded yesterday, so it should be the latest one.

**Comment by mtwebster** [comment] 2024-07-30 14:02
Duplicate of https://github.com/linuxmint/mintinstall/issues/423, fixed

**Closed by mtwebster** 2024-07-30 14:02 UTC
