### ISSUE TITLE
Flatpak: gnome-maps seemed to install but would not run

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintinstall#176] opened 2018-01-10 04:27 UTC
**What I did**

Open Software Centre.
Clicked 'flatpaks' on the left.
Select gnome-maps.
Clicked install and was surprised not to be asked for a password. A progress bar appeared.
The progress bar disappeared.
I tried and failed to find gnome-maps on my system. 

**What should happen**

The user should be able to run the installed application easily. Or if the application did not install, then the user should be hold.

MintInstall 7.8.9.

**Comment by xenopeek** [comment] 2018-01-29 19:36
Was this the first Gnome application Flatpak you installed? In that case it would first install a (big) Gnome runtime. That can take quite a while and will silently fail if you're testing this from the LiveISO.

**Comment by CottonEaster** [comment] 2018-01-29 19:58
> Was this the first Gnome application Flatpak you installed? 

Yes.

> That can take quite a while and will silently fail if you're testing this from the LiveISO.

I was running a proper install, not a LiveISO.

**Comment by xenopeek** [comment] 2018-01-29 20:01
Have you since installed any other Gnome application Flatpak? What does the command `flatpak list` tell you? If there is Gnome runtime on it and no Gnome Maps, try again but this time start `mintinstall` from the terminal so you can capture any errors from there. Share the terminal output and what `flatpak list` replied.

**Comment by JosephMcc** [comment] 2018-01-29 20:06
Keep in mind also that the first time you run a flatpak application it can take a very long time to start. This is a know flatpak issue and only occurs on the first run.

**Comment by clefebvre** [comment] 2018-02-02 09:31
Closing, the issue describes an observation, not a bug.

When installing a flatpak, if the runtime is missing, a UI element indicates that this is happening and invites the user to be patient. On completion, a launch button is provided to start the app.

**Closed by clefebvre** 2018-02-02 09:31 UTC
Labels: Gathering Info
