### ISSUE TITLE
Error installing Thunderbird (Flathub) via Mint's Software Manager

### ISSUE THREAD

**Issue by ovari** [linuxmint/mintinstall#260] opened 2019-09-19 22:42 UTC
Add `runtime/org.freedesktop.Platform/x86_64/19.08` to the dependency list and automatically install if required.

![image](https://user-images.githubusercontent.com/17465872/65286271-503e4380-db82-11e9-9930-ccb32d64fb32.png)

![image](https://user-images.githubusercontent.com/17465872/65286278-56342480-db82-11e9-8101-414da9a0ac9a.png)

What do you think?

Thank you

https://github.com/flathub/org.mozilla.Thunderbird/issues/80#issuecomment-533113014

**Comment by ovari** [comment] 2019-09-19 22:44
What version of `Flatpak` does the `Software Manager` use?

https://github.com/flathub/org.mozilla.Thunderbird/issues/80#issuecomment-533083101

**Comment by mtwebster** [comment] 2019-09-19 22:44
The 19.08 runtime needs a newer version of flatpak than is currently available in Mint

**Comment by ovari** [comment] 2019-09-19 22:46
Can the `flatpak` version in Mint please be updated? Thank you

**Comment by mtwebster** [comment] 2019-09-19 22:49
Actually it's the `org.freedesktop.Platform.openh264` package that's failing due to the flatpak version.

**Comment by mtwebster** [comment] 2019-09-19 22:52
You can try using the ppa version (https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak)

We'll see if we can get that updated in Mint as well

**Comment by ovari** [comment] 2019-09-19 22:52
Is the flatpak version in Mint >= 1.4.2?

**Comment by ovari** [comment] 2019-09-19 22:56
Prefer to wait for Mint update. Can you please advise how long it will take to update `flatpak` in Mint? Thank you

**Comment by mtwebster** [comment] 2019-09-19 23:02
Not sure.  It shouldn't be an issue, so hopefully very soon.

**Comment by ovari** [comment] 2019-09-19 23:05
Thank you. Would you update Mint to `flatpak` version 1.4.2 or 1.4.3? Thank you

**Comment by feren** [comment] 2019-09-22 13:21
I still can reproduce this issue even with Flatpak on 1.4.3 except now it's merely complaining that the troublesome package isn't installed.

**Comment by feren** [comment] 2019-09-22 13:23
```
~$ flatpak install flathub org.freedesktop.Platform.openh264
Looking for matches…


        ID                                   Arch     Branch   Remote    Download
 1. [✗] org.freedesktop.Platform.openh264    x86_64   19.08    flathub   593.6 kB / 593.4 kB

Error: org.freedesktop.Platform.openh264 not installed
error: Failed to install org.freedesktop.Platform.openh264: While trying to apply extra data: runtime/org.freedesktop.Platform/x86_64/19.08 not installed
```

**Comment by clefebvre** [comment] 2019-09-23 09:48
Fixed in mintcommon 2.0.6.

**Closed by clefebvre** 2019-09-23 09:48 UTC

**Comment by ovari** [comment] 2019-09-23 12:16
Thank you for the fix to enable `Thunderbird (Flathub)` to install.

1. Should the menu item be changed from
`Thunderbird`
to
`Thunderbird Mail`
?

It would help if someone was looking searching for `mail`.

2. Should the descriptions match? Should the Flathub description be changed from
`Send and Receive Email`
to
`Send and receive email with Thunderbird`
?

What do you think?

Thank you

![image](https://user-images.githubusercontent.com/17465872/65424721-8ebc5280-de4f-11e9-8dd5-9475d84d992c.png)

![image](https://user-images.githubusercontent.com/17465872/65424727-94b23380-de4f-11e9-8412-de504a500289.png)

**Comment by ovari** [comment] 2019-09-23 12:46
Opening `Thunderbird (Flathub)` and adding an existing email account (which was already in the non-flatpak Thunderbird), Thunderbird unexpected disappeared (terminated?). Clicking on `Thunderbird (Flathub)` no longer opened Thunderbird. Are you able to reproduce?
