### ISSUE TITLE
Segfault browsing flatpak of GIMP

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintinstall#340] opened 2022-08-31 04:14 UTC
Mint 21 Cinnamon, upgraded in-place (without errors) from Mint 20.3.

I selected the 'flatpak' category. I searched for and found GIMP. I clicked the result. I saw a spinner. Then MintInstall crashed to desktop. I have no crash-dump - when I ran MintReport, it told me I had to install a package and reboot - but I see this in the syslog:

`mintinstall[7376]: segfault at 0 ip 0000000000000000 sp 00007ffc20a23798 error 14 in python3.10[55b975ba8000+6d000]`

Upon re-opening MintInstall, I was able to install the GIMP flatpak and run it.

**Comment by mantuoliveira** [comment] 2022-09-06 16:07
I can confirm this. It happened when trying to install Octave and Bottle, both via flatpak.

**Comment by mtwebster** [comment] 2022-09-06 16:26
Can't reproduce.

Can you check System Reports for crash data? (System Reports -> Crash Reports, select, Local Files, crash.tar.gz)

**Comment by LinuxOnTheDesktop** [comment] 2022-09-06 23:56
Currently on neither of my Mint PCs can I reproduce the problem. Sorry.

**Comment by mtwebster** [comment] 2022-12-01 15:57
We've revamped most of flatpak handling, I'm going to close this.  If it occurs again in 8.2 please open a new issue.

**Closed by mtwebster** 2022-12-01 15:57 UTC
