### ISSUE TITLE
mintinstall removes important packages like lightdm and slick-greeter when there are pending updates

### ISSUE THREAD

**Issue by fabianbeil** [linuxmint/mintinstall#332] opened 2022-01-18 18:30 UTC
Distro: Linux Mint Cinnamon 20.1 (64bit), Cinnamon 4.8.6

## Faulty behaviour:
Under certain conditions when there are pending updates, mintinstall removes important system packages when trying to install new packages (tested with `virt-manager`). The problem does **not** persist when installing via apt or synaptic.

When I tried to install virt-manager via mintinstall, there was a notification that some packages would have to be removed which I did not carefully check at the time. After reboot, lightdm, slick-greeter, several other packages including network-manager, mint-meta-core and mint-meta-cinnamon were gone and I had a gdm3 greeter, some minimal version of gnome and no networking at all. The full discussion including apt logfiles is here: [https://forums.linuxmint.com/viewtopic.php?f=47&t=365599](https://forums.linuxmint.com/viewtopic.php?f=47&t=365599)

## Steps to reproduce
1. Download iso of Linux Mint Cinnamon 64bit 20.3 
2. Install Mint in a VirtualBox VM, do not update.
3. Install virt-manager via Software Manager
4. reboot

The behaviour is different when using a qemu-vm, then mintinstall shows an error about unresolved dependencies
`system-container: Depends: systemd (=245.4-4ubuntu3.15) but 245.4-4ubuntu3.15 is being installed` (translated from German)

Apparently there are other conditions that lead to this error, i.e. when the wrong packages have pending updates. I can't give an exact description as an apt update/upgrade got rid of the behaviour.

**Comment by xenopeek** [comment] 2022-01-18 19:16
The meta packages cause a set of other packages to be installed. Removing the meta packages doesn't remove software or other (non-meta) packages. They are likely being removed as consequence of removing the other packages you mention so those should have the focus, not the meta packages.

**Comment by mtwebster** [comment] 2022-10-24 19:40
I can't reproduce this in either a live 20.3 or a freshly installed 20.3 - 

mintinstall:
```
mtwebster@mtwebster-VirtualBox:~$ mintinstall
MintInstall: Detected system architecture: 'x86_64'
Installer: User pkgcache is most recent, using it.
MintInstall: Deleting old screenshots
MintInstall: No new reviews
Installer: Calculating changes required for APT package: virt-manager
For install: ['libusbredirparser1', 'seabios', 'libgovirt2', 'virtinst', 'osinfo-db', 'python3-distutils', 'ipxe-qemu', 'libxml2-utils', 'libvirt-daemon-system-systemd', 'gir1.2-spiceclientgtk-3.0', 'libibverbs1', 'libosinfo-1.0-0', 'spice-client-glib-usb-acl-helper', 'msr-tools', 'librbd1', 'ibverbs-providers', 'qemu-system-x86', 'python3-libxml2', 'libusbredirhost1', 'libvirt-clients', 'librdmacm1', 'libnss-mymachines', 'libspice-server1', 'libvirt-daemon-driver-storage-rbd', 'libpmem1', 'libphodav-2.0-common', 'libgovirt-common', 'ovmf', 'libvirglrenderer1', 'libgvnc-1.0-0', 'libvirt-daemon-driver-qemu', 'qemu-system-data', 'qemu-utils', 'libvirt-daemon-system', 'libcacard0', 'gir1.2-gtk-vnc-2.0', 'sharutils', 'ipxe-qemu-256k-compat-efi-roms', 'python3-lib2to3', 'virt-manager', 'virt-viewer', 'libspice-client-glib-2.0-8', 'libvirt-glib-1.0-0', 'qemu-kvm', 'libvirt0', 'libfdt1', 'libslirp0', 'libiscsi7', 'libphodav-2.0-0', 'python3-libvirt', 'systemd-container', 'cpu-checker', 'gir1.2-libvirt-glib-1.0', 'qemu-block-extra', 'gir1.2-libosinfo-1.0', 'libspice-client-gtk-3.0-5', 'librados2', 'libgtk-vnc-2.0-0', 'qemu-system-common', 'gir1.2-spiceclientglib-2.0', 'qemu-system-gui', 'libvirt-daemon']
For removal: []
For upgrade: ['libsystemd0', 'systemd-coredump', 'systemd-timesyncd', 'systemd-sysv', 'libpam-systemd', 'systemd', 'libnss-systemd']
```
apt:
```
mtwebster@mtwebster-VirtualBox:~$ apt install virt-manager
[sudo] password for mtwebster:         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  cpu-checker gir1.2-gtk-vnc-2.0 gir1.2-libosinfo-1.0 gir1.2-libvirt-glib-1.0 gir1.2-spiceclientglib-2.0 gir1.2-spiceclientgtk-3.0
  ibverbs-providers ipxe-qemu ipxe-qemu-256k-compat-efi-roms libcacard0 libfdt1 libgovirt-common libgovirt2 libgtk-vnc-2.0-0
  libgvnc-1.0-0 libibverbs1 libiscsi7 libnss-mymachines libnss-systemd libosinfo-1.0-0 libpam-systemd libphodav-2.0-0
  libphodav-2.0-common libpmem1 librados2 librbd1 librdmacm1 libslirp0 libspice-client-glib-2.0-8 libspice-client-gtk-3.0-5
  libspice-server1 libsystemd0 libusbredirhost1 libusbredirparser1 libvirglrenderer1 libvirt-clients libvirt-daemon
  libvirt-daemon-driver-qemu libvirt-daemon-driver-storage-rbd libvirt-daemon-system libvirt-daemon-system-systemd libvirt-glib-1.0-0
  libvirt0 libxml2-utils msr-tools osinfo-db ovmf python3-distutils python3-lib2to3 python3-libvirt python3-libxml2 qemu-block-extra
  qemu-kvm qemu-system-common qemu-system-data qemu-system-gui qemu-system-x86 qemu-utils seabios sharutils
  spice-client-glib-usb-acl-helper systemd systemd-container systemd-coredump systemd-sysv systemd-timesyncd virt-viewer virtinst
Suggested packages:
  libosinfo-l10n libvirt-daemon-driver-lxc libvirt-daemon-driver-vbox libvirt-daemon-driver-xen libvirt-daemon-driver-storage-gluster
  libvirt-daemon-driver-storage-zfs numad auditd nfs-common open-iscsi radvd systemtap zfsutils samba vde2 debootstrap sharutils-doc
  bsd-mailx | mailx python3-guestfs ssh-askpass
The following NEW packages will be installed:
  cpu-checker gir1.2-gtk-vnc-2.0 gir1.2-libosinfo-1.0 gir1.2-libvirt-glib-1.0 gir1.2-spiceclientglib-2.0 gir1.2-spiceclientgtk-3.0
  ibverbs-providers ipxe-qemu ipxe-qemu-256k-compat-efi-roms libcacard0 libfdt1 libgovirt-common libgovirt2 libgtk-vnc-2.0-0
  libgvnc-1.0-0 libibverbs1 libiscsi7 libnss-mymachines libosinfo-1.0-0 libphodav-2.0-0 libphodav-2.0-common libpmem1 librados2 librbd1
  librdmacm1 libslirp0 libspice-client-glib-2.0-8 libspice-client-gtk-3.0-5 libspice-server1 libusbredirhost1 libusbredirparser1
  libvirglrenderer1 libvirt-clients libvirt-daemon libvirt-daemon-driver-qemu libvirt-daemon-driver-storage-rbd libvirt-daemon-system
  libvirt-daemon-system-systemd libvirt-glib-1.0-0 libvirt0 libxml2-utils msr-tools osinfo-db ovmf python3-distutils python3-lib2to3
  python3-libvirt python3-libxml2 qemu-block-extra qemu-kvm qemu-system-common qemu-system-data qemu-system-gui qemu-system-x86
  qemu-utils seabios sharutils spice-client-glib-usb-acl-helper systemd-container virt-manager virt-viewer virtinst
The following packages will be upgraded:
  libnss-systemd libpam-systemd libsystemd0 systemd systemd-coredump systemd-sysv systemd-timesyncd
7 upgraded, 62 newly installed, 0 to remove and 394 not upgraded.
Need to get 30.2 MB of archives.
After this operation, 115 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
Same after running apt-update (but not upgrading any packages).

I'm not trying to say this never happened, but it's not happening for me. I will say that the backend we've been using in mintinstall could be pretty brain-dead at times (aptdaemon), and we had some issues with dependencies when first getting Mint 20 ready with nvidia drivers, codecs and other things. So this type of stuff is definitely credible to me.

We're currently putting quite a bit of work into mintinstall, including changing the apt backend (to packagekit, which uses the same resolver as the apt command), which, in testing so far, seems to be a lot better at handling dependencies. Once that gets merged I'll probably close this issue. If there are any similar problems using the new backend, we'll address them at that time.

**Comment by mtwebster** [comment] 2022-12-01 15:59
Closing this as 8.2 (and mint-common 2.2.1) have the mentioned improvements.

**Closed by mtwebster** 2022-12-01 15:59 UTC
